### PR TITLE
fix(snippet-bot): do not add a useless comment

### LINKED ISSUE #2021: snippet-bot: pull request that has never touched region tags should not have comment added
When a pull request is made editing a file in a repository that is not related to samples, as an example updating configuration. It feels a bit strange that snippet bot leaves a comment (see #2020).

This creates additional confusion for repositories which have no samples, e.g.,

* gax-nodejs.
* google-auth-library.
* repo-automation-bots.
* release-please
* gaxios
* teeny-request
* discovery-artifact-manager
* code-suggester
* node-gtoken

It also creates confusion for handwritten libraries, where code being added may or may not be touching samples, e.g.,

* nodejs-spanner
* nodejs-storage

---

Perhaps rather than adding the snippet bot comment, we could add an emoji to the PR, like merge-on-green does?

Or perhaps the status check is enough?

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #2021

When the PR is not modifying any region tags, the bot will not add
a new comment, but if there's already a comment, it will update it.

### CODE REVIEW

File: packages/snippet-bot/test/snippet-bot.ts [hunk 1]
```diff
@@ -603,15 +595,7 @@ describe('snippet-bot', () => {
...
-        .reply(200, [])
-        .post(
-          '/repos/tmatsuo/repo-automation-bots/issues/14/comments',
-          body => {
-            snapshot(body);
-            return true;
-          }
-        )
-        .reply(200);
+        .reply(200, []);
```
Comment (bcoe) [inline packages/snippet-bot/test/snippet-bot.ts:598]: Would it be possible to add a test for the two new cases:

"no comment added if no samples modified"

"existing comment updated, if comment existed and samples no longer updated".

**Review by bcoe — CHANGES_REQUESTED** [review]

File: packages/snippet-bot/test/snippet-bot.ts (hunk 1 above)
Comment (tmatsuo) [reply packages/snippet-bot/test/snippet-bot.ts:598]: Added 2 tests, PTAL

**Review by bcoe — APPROVED** [review]
ship it 👌
