### PR TITLE
fix(label-sync): quit when failed to get config

### LINKED ISSUE #1639: bug(label_sync): HttpError: Resource not accessible by integration
It's likely for private repo, so starting with p2.

```
    HttpError: Resource not accessible by integration
        at /workspace/node_modules/@octokit/request/dist-node/index.js:66:23
        at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:445:12)
        at async getConfigFile (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:103:9)
        at async getConfigFiles (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:203:29)
        at async composeConfigGet (/workspace/node_modules/@probot/octokit-plugin-config/dist-node/index.js:283:17)
        at async Context.config (/workspace/node_modules/probot/lib/context.js:157:35)
        at async Object.loadConfig (/workspace/build/src/label-sync.js:132:13)
        at async /workspace/build/src/label-sync.js:95:37
        at async Promise.all (index 0) 
```

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1639

### CODE REVIEW

File: packages/label-sync/src/label-sync.ts [hunk 1]
```diff
@@ -114,10 +125,21 @@ export function handler(app: Probot) {
...
+    } catch (err) {
+      err.message =
+        'Error reading configuration for ' +
+        `${c.payload.repository.full_name}, skipping: ${err.message}`;
+      logger.error(err);
+      return;
+    }
     if (remoteConfiguration?.ignored) {
-      logger.info(`skipping repository ${repo}`);
+      logger.info(`skipping repository ${c.payload.repository.full_name}`);
```
Comment (danielbankhead) [inline packages/label-sync/src/label-sync.ts:142]: Optional: This logic looks the same as above; could be wrapped in a shared function

**Review by danielbankhead — APPROVED** [review]

**Comment by tmatsuo** [comment]
@danielbankhead Thanks!
