### PR TITLE
fix(snippet-bot): use git-file-utils for fetching files

### LINKED ISSUE #2703: snippet-bot: use Git Data API for fetching files
If a PR has a large file, it gets an error like this:
```
HttpError: This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.: {"resource":"Blob","field":"data","code":"too_large"}"
```

In this case, the bot ignores that file. This is probably ok because a file larger than 1MB likely doesn't contain any region tags.

However, it's still theoretically possible so it's better to migrate to Git Data API for fetching files.

Pragmatically I don't think we'll really need to fix this, so marking as p3. If we ever see such a file, I'll bump the priority to P2.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #2703

### CODE REVIEW

File: packages/snippet-bot/src/snippet-bot.ts [hunk 1]
```diff
@@ -301,14 +299,10 @@ async function scanPullRequest(
         tagsFound = true;
       }
     } catch (e) {
-      const err = e as RequestError & Error;
-      // Ignoring 403/404 errors.
-      if (err.status === 403 || err.status === 404) {
-        logger.info(
-          `ignoring 403/404 errors upon fetching ${file}: ${err.message}`
-        );
+      if (e instanceof FileNotFoundError) {
```
Comment (bcoe) [inline packages/snippet-bot/src/snippet-bot.ts:302]: 403s will now be fatal? Do we know why were ignoring 403s previously?

**Review by bcoe — APPROVED** [review]
This seems like a really nice cleanup (along with addressing the bug).

File: packages/snippet-bot/src/snippet-bot.ts (hunk 1 above)
Comment (tmatsuo) [reply packages/snippet-bot/src/snippet-bot.ts:302]: I don't remember, but probably a mistake :)
