### PR TITLE
fix: (owl-bot) add ignore files list to refreshConfigs function

### LINKED ISSUE #4980: How do I get owlbot to ignore a template file?
https://github.com/googleapis/google-cloud-node/issues/3888

This file isn't a real .Owlbot.yaml file, but I cannot close the issue for good.

### PR DESCRIPTION
**Pull request by sofisl**
Fixes #4980

### CODE REVIEW

File: packages/owl-bot/src/handlers.ts [hunk 1]
```diff
@@ -31,6 +31,9 @@ import {shouldIgnoreRepo} from './should-ignore-repo';
 
 type ListReposResponse = Endpoints['GET /orgs/{org}/repos']['response'];
 
+export const CONFIG_PATHS_TO_SKIP = [
+  'packages/gapic-node-templating/templates/bootstrap-templates/.OwlBot.yaml',
```
Comment (SurferJeffAtGoogle) [inline packages/owl-bot/src/handlers.ts:35]: Add a comment explaining why this path is being skipped.

File: packages/owl-bot/src/handlers.ts [hunk 2]
```diff
@@ -301,16 +304,18 @@ export async function refreshConfigs(
...
-        octokit,
-        githubRepo.owner,
-        githubRepo.repo,
-        badConfig.path + ' is broken.',
-        [
-          'This repo will not receive automatic updates until this issue is fixed.\n',
-          ...badConfig.errorMessages,
-        ].join('\n* ')
-      );
+      if (!CONFIG_PATHS_TO_SKIP.includes(badConfig.path)) {
```
Comment (SurferJeffAtGoogle) [inline packages/owl-bot/src/handlers.ts:307]: When the path is skipped, please write a log statement citing the path that was skipped and why.

**Review by SurferJeffAtGoogle — CHANGES_REQUESTED** [review]

**Review by SurferJeffAtGoogle — APPROVED** [review]
