### PR TITLE
fix: allow multiple paths to --config-file

### LINKED ISSUE #3978: Owlbot: Allow owlbot to accept multiple config files while running locally.
In the [owlbot usage guide](go/owlbot-howto#how-will-i-test-my-githubowlbotyaml-file), the following command is run to test the .OwlBot.yaml file for a monorepo. 
```
docker run --rm --user $(id -u):$(id -g) \
  -v $(pwd):/repo -v /tmp/googleapis-gen:/googleapis-gen -w /repo \
  gcr.io/cloud-devrel-public-resources/owlbot-cli:latest copy-code \
  --source-repo=/googleapis-gen \
  --config-file=path/to/.OwlBot.yaml
  ```
Since this is in a monorepo, a feature to test multiple services at once is useful. Please add a feature to allow `--config-file` to accept multiple .OwlBot.yaml files.

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
Fixes #3978

### CODE REVIEW

File: packages/owl-bot/src/copy-code.ts [hunk 1]
```diff
@@ -787,7 +787,7 @@ export async function copyCode(
   sourceCommitHash: string,
   destDir: string,
   workDir: string,
-  yaml: OwlBotYaml,
+  yamls: OwlBotYaml[],
```
Comment (tmatsuo) [inline packages/owl-bot/src/copy-code.ts:790]: Any other caller other than the cli?

Comment (SurferJeffAtGoogle) [reply packages/owl-bot/src/copy-code.ts:790]: Nope.  Other code paths call other functions within copy-code.ts.
