### PR TITLE
fix(policy): do not throw for missing branch

### LINKED ISSUE #1989: bug(policy): crashes with HTTPError "Branch not found"
```
"HttpError: Branch not found
    at /workspace/node_modules/@octokit/request/dist-node/index.js:76:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:450:12)
    at async getBranchHead (/workspace/node_modules/code-suggester/build/src/github/branch.js:37:25)
    at async Object.branch (/workspace/node_modules/code-suggester/build/src/github/branch.js:107:25)
    at async retry.retries (/workspace/node_modules/code-suggester/build/src/index.js:105:48)
    at async Object.createPullRequest (/workspace/node_modules/code-suggester/build/src/index.js:105:24)
    at async Changer.addFile (/workspace/build/src/changer.js:94:9)
    at async Changer.submitFixes (/workspace/build/src/changer.js:114:13)"
```

I think we can ignore such cases.

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Fixes #1989

### CODE REVIEW

File: packages/policy/src/changer.ts [hunk 1]
```diff
@@ -115,17 +119,30 @@ export class Changer {
...
+        upstreamOwner: this.owner,
+        upstreamRepo: this.name,
+        fork: false,
+        primary: this.repo.default_branch,
+        retry: 0,
+        branch: `policy-bot-${uuid()}`,
+      });
+    } catch (e) {
+      const err = e as Error;
+      if (err.message === 'Branch not found') {
```
Comment (tmatsuo) [inline packages/policy/src/changer.ts:136]: Nit: it will bubble up when Github changes the error message.

**Review by tmatsuo — APPROVED** [review]
