### PR TITLE
fix(owlbot): address bugs with running owlbot against fork

### LINKED ISSUE #1717: Adding "owlbot:run" does not work for external contributors
This is most likely a bug related to us using the wrong `owner`/`repo` when kicking off a post-processing job.

### PR DESCRIPTION
**Pull request by bcoe**
API calls that interact with the PR must be made against base, but API calls that
clone source should be made against the fork.

See: https://github.com/googleapis/nodejs-phishing-protection/pull/300
Fixes #1717

### CODE REVIEW

File: packages/owl-bot/test/owl-bot.ts [hunk 1]
```diff
@@ -708,7 +708,7 @@ describe('owlBot', () => {
     image: node
     digest: sha256:9205bb385656cd196f5303b03983282c95c2dfab041d275465c525b501574e5c`;
     const githubMock = nock('https://api.github.com')
-      .get('/repos/bcoe/owl-bot-testing/pulls/33')
+      .get('/repos/rennie/owl-bot-testing/pulls/33')
```
Comment (bcoe) [inline packages/owl-bot/test/owl-bot.ts:711]: This bug was caught by existing tests.

File: packages/owl-bot/src/bin/commands/test-webhook.ts [hunk 2]
```diff
@@ -70,7 +70,8 @@ export const testWebhook: yargs.CommandModule<{}, Args> = {
       })
       .option('trigger', {
         describe: 'cloud build trigger to run',
-        default: 'ff6ace31-d5f9-41ff-a92c-459ed1755e35',
+        // OwlBot post processor image:
+        default: '637fc67f-fec0-4b62-a5f1-df81a6808c17',
```
Comment (bcoe) [inline packages/owl-bot/src/bin/commands/test-webhook.ts:74]: I had the wrong default trigger.

File: packages/owl-bot/src/owl-bot.ts [hunk 3]
```diff
@@ -253,7 +253,7 @@ const runPostProcessor = async (
     );
   }
   // Fetch the .Owlbot.lock.yaml from the head ref:
```
Comment (tmatsuo) [inline packages/owl-bot/src/owl-bot.ts:255]: The comment seems stale.
