### PR TITLE
fix: look deeper into pull request history

### LINKED ISSUE #2829: OwlBot repeatedly reopening PRs for the same change/API combination
Last night Ruby made a pair of "global" changes (cl/406897753 and cl/406979172) to its generator configs that affected large numbers of libraries in its [monorepo](https://github.com/googleapis/google-cloud-ruby). We expected that OwlBot would create a set of ~200 PRs for one of those changes, and another set of ~100 PRs for the other. In order to reduce the noise, we "pre-empted" these changes by running the generation/owlbot pipeline locally and merging a [single PR](https://github.com/googleapis/google-cloud-ruby/pull/14492) aggregating all the expected changes to all libraries (since we're a monorepo) before OwlBot ran. We expected, then, that OwlBot would open and then immediately close (since the change is already present) its two series of PRs (300-ish in all) and be done.

OwlBot did open and close the series of PRs as expected, but then repeated the process, and as of this morning about 9am is on its fourth iteration, having gone through >1000 PRs and counting. To be clear, this means 4 PRs for the _same_ change/API combination. Example: https://github.com/googleapis/google-cloud-ruby/pull/14608 https://github.com/googleapis/google-cloud-ruby/pull/14859 https://github.com/googleapis/google-cloud-ruby/pull/15137 https://github.com/googleapis/google-cloud-ruby/pull/15274 and counting.

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
Fixes #2829

### CODE REVIEW

File: packages/owl-bot/src/copy-code.ts [hunk 1]
```diff
@@ -587,17 +631,54 @@ export async function copyExists(
...
+    };
+    const cacheKey = keyFrom('pulls', request);
+    const cachedPulls = cache.get(cacheKey);
+    let pulls;
+    if (cachedPulls) {
+      pulls = cachedPulls;
+    } else {
+      pulls = await octokit.pulls.list({...request});
+      cache.set(cacheKey, pulls);
+    }
```
Comment (chingor13) [inline packages/owl-bot/src/copy-code.ts:650]: nit: I might have designed this as a read-through cache (just ask the cache for page x of issues|pulls and it'll either return the cached version or fetch it, store it, and return it to you), rather than exposing it as a `Map` that you `get` and `set` on. Internally, it could do this same logic, but hide that from the calling code.

```
const cache = newRepoHistoryCache(octokit);
...
const pulls = await cache.fetchPulls(request);
```

**Review by chingor13 — APPROVED** [review]

File: packages/owl-bot/src/copy-code.ts [hunk 2]
```diff
@@ -272,7 +272,7 @@ export async function copyCodeAndCreatePullRequest(
   const token = await octokitFactory.getGitHubShortLivedAccessToken();
   // Octokit token may have expired; refresh it.
   const octokit = await octokitFactory.getShortLivedOctokit(token);
-  if (await copyExists(octokit, destRepo, dest.sourceCommitHash)) {
+  if (await copyExists(octokit, destRepo, dest.sourceCommitHash, 100)) {
```
Comment (chingor13) [inline packages/owl-bot/src/copy-code.ts:275]: Should this be 1000?

File: packages/owl-bot/src/copy-code.ts (hunk 1 above)
Comment (SurferJeffAtGoogle) [reply packages/owl-bot/src/copy-code.ts:650]: I expect the calling code to treat it as an opaque value, as it currently does.  Note, that I could completely change type RepoHistoryCache without changing any of the calling code.

File: packages/owl-bot/src/copy-code.ts (hunk 2 above)
Comment (SurferJeffAtGoogle) [reply packages/owl-bot/src/copy-code.ts:275]: This is the final check before creating a pull request, to make sure a parallel process didn't create the same pull request.  That would be very recent because the processes are running in parallel, so checking the most recent 100 is sufficient.  Also, in this case we deliberately omit a cache.

File: packages/owl-bot/src/copy-code.ts (hunk 1 above)
Comment (SurferJeffAtGoogle) [reply packages/owl-bot/src/copy-code.ts:650]: If RepoCacheHistory ever gets passed to another function, then I'll wrap it in a type as you described.

**Review by chingor13 — APPROVED** [review]
