### PR TITLE
fix: look at bot name, provide more helpful error message

### LINKED ISSUE #1257: generate-bot fails with "You used an invalid character, like an integer. Please try again."
```$ npm run generate-bot

> generate-bot@1.1.0 generate-bot /usr/local/google/home/rennie/repo-automation-bots/packages/generate-bot
> node build/src/run.js

✔ What is the name of the program? · owl-bot
✔ What is the description of the program? · Watches client library dependencies and triggers code to be regenerated.

✔ This package will be saved in /packages/yourProgramName unless you specify another location and directory name here relative to /usr/local/google/home/rennie/repo-automation-bots/packages/generate-bot :  · 


You used an invalid character, like an integer. Please try again.
```

I don't know which of the 60 characters or so I typed is invalid.

### PR DESCRIPTION
**Pull request by sofisl**
Just trying to chip away...
Fixes #1257

### CODE REVIEW

File: packages/generate-bot/src/main.ts [hunk 1]
```diff
@@ -26,18 +26,12 @@ export interface ProgramOptions {
...
-    .replace(/"/g, '')
-    .replace(/}$/, '');
+  const validName = /[^-A-Za-z_]+/;
+  const botName = opts.programName;
 
-  if (validName.test(string)) {
+  if (validName.test(botName)) {
     console.log(
-      'You used an invalid character, like an integer. Please try again.'
+      'Only letters, hyphens, are underscores are permitted in the bot name. Please try again.'
```
Comment (tmatsuo) [inline packages/generate-bot/src/main.ts:34]: s/are/and/ ?

**Review by tmatsuo — APPROVED** [review]
