### PR TITLE
fix(snippet-bot): make formatBody resilient to an empty body

### LINKED ISSUE #4251: snippet-bot: full scan fails when the issue body is empty
The error log:
```
Failed to scan files: Cannot read property 'indexOf' of null
```

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #4251

### CODE REVIEW

**Review by bcoe — APPROVED** [review]

File: packages/snippet-bot/test/utils.ts [hunk 1]
```diff
@@ -59,6 +59,19 @@ describe('formatBody', () => {
       )
     );
   });
+  it('should add contents to an empty body', () => {
+    const result = formatBody(
+      undefined as unknown as string,
```
Comment (bcoe) [inline packages/snippet-bot/test/utils.ts:64]: gross bug!
