### PR TITLE
fix: examine all repos even when one fails

### LINKED ISSUE #3465: owl-bot runs owlbot-maybe-create-pull-request-for-lock-update for archived repositories
Then the build fails ([an example build](https://pantheon.corp.google.com/cloud-build/builds;region=global/e248d031-7c80-4325-be4f-2abdb47de8a6?project=repo-automation-bots)).

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
Fixes #3465

### CODE REVIEW

File: packages/owl-bot/src/handlers.ts [hunk 1]
```diff
@@ -232,9 +232,8 @@ export async function scanGithubForConfigs(
       const err = e as RequestError;
       if (err.status === 404) {
         logger.warn(`received 404 refreshing ${githubOrg}/${repo.name}`);
-        continue;
       } else {
-        throw err;
+        logger.error(`error refreshing ${githubOrg}/${repo.name}: ${e}`);
```
Comment (tmatsuo) [inline packages/owl-bot/src/handlers.ts:236]: This can happen because the repo has a bad config?

Comment (SurferJeffAtGoogle) [reply packages/owl-bot/src/handlers.ts:236]: Perhaps it can happen for that reason too.  I saw it happen because a repo was private.

**Review by chingor13 — APPROVED** [review]
