### PR TITLE
fix(release-please): prevent crashes in findBranchConfiguration

### LINKED ISSUE #1781: bug(release-please): release-please crashes with `TypeError: config.branches.find is not a function`
It seems happening for `googleapis/java-compute`
```
    TypeError: config.branches.find is not a function
        at findBranchConfiguration (/workspace/build/src/release-please.js:63:35)
        at /workspace/build/src/release-please.js:155:37
        at runMicrotasks (<anonymous>)
        at async Promise.all (index 0)
        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21
```

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1781

### CODE REVIEW

File: packages/release-please/src/release-please.ts [hunk 1]
```diff
@@ -118,13 +118,17 @@ function findBranchConfiguration(
...
+  try {
+    const found = config.branches.find(branchConfig => {
+      return branch === branchConfig.branch;
+    });
+    if (found) {
+      return found;
+    }
+  } catch (err) {
+    err.message = `got an error finding the branch config: ${err.message}`;
+    logger.error(err);
```
Comment (chingor13) [inline packages/release-please/src/release-please.ts:130]: Should we debug log the offending configuration as well?

**Review by chingor13 — APPROVED** [review]

File: packages/release-please/src/release-please.ts (hunk 1 above)
Comment (tmatsuo) [reply packages/release-please/src/release-please.ts]: done
