### PR TITLE
fix: add appended commit's message to pr body

### LINKED ISSUE #3179: FR(owl-bot): PR body is not updated when owlbot appends commits to an open PR
Owlbot opened PR: https://github.com/googleapis/python-billingbudgets/pull/174 on February 10th. One day later, owlbot added commit `ade2836` (see screenshot below) which included conventional commit messages however these new conventional commit messages weren't added to the PR body. After I clicked the `Regenerate this pull request now` button , the owlbot regenerated the PR and the conventional commit messages appeared in the PR body. Ideally owlbot should append conventional commit messages to the PR body as new commits are added. Another solution is for owlbot to automatically regenerate the entire PR (similar to clicking the 'regenerate this pull request now' checkbox) rather than adding separate commits.

image

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
Fixes #3179

### CODE REVIEW

**Review by parthea — APPROVED** [review]

File: packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts [hunk 1]
```diff
@@ -494,12 +500,16 @@ Copy-Tag: ${copyTagFrom('.github/.OwlBot.yaml', abcCommits[2])}`;
     assert.strictEqual(gitLog, `${commitMessage2}\n\n${commitMessage1}\n\n`);
 
     // Confirm the pull request body was updated.
+    // The first line of commitMessage2 becomes PR title.
+    const newline = commitMessage2.indexOf('\n');
+    const body2 = commitMessage2.slice(newline).trim();
     assert.deepStrictEqual(pulls.updates, [
       {
-        body: `${EMPTY_REGENERATE_CHECKBOX_TEXT}\n\n${commitMessage2}\n\n${commitMessage1}\n\n`,
+        body: `${EMPTY_REGENERATE_CHECKBOX_TEXT}\n\n${body2}\n\n${commitMessage1}\n\n`,
```
Comment (chingor13) [inline packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts:508]: nit: it might be nice to use something like `snap-shot-it` to record the full message. We're building the expected output so reading the test is hard to see what the final output looks like.

**Review by chingor13 — APPROVED** [review]

File: packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts (hunk 1 above)
Comment (SurferJeffAtGoogle) [reply packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts:508]: I tried, but the problem is the copy-tag varies with the source repo commit hash, and the source repo commit hash varies every time the test runs.
