### PR TITLE
fix(snippet-bot): use products.json for region_tag_prefix

### LINKED ISSUE #1101: bug(snippet-bot): cloudrun prefix is considered as a violation
snippet-bot started to check product prefixes. Now it is using product short names for product prefix, but in some cases, the product prefix is different from the product short names (e.g. cloudrun v.s. run).

We should use `region_tag_prefix` instead of `api_shortname`. Now we're waiting for the `api.json` to have that new field.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1101

Locally it works fine with using the dev bucket. Currently the new `products.json` file is not yet deployed to the prod bucket, so we can not merge this yet.

### CODE REVIEW

File: packages/snippet-bot/src/violations.ts [hunk 1]
```diff
@@ -24,18 +24,24 @@ export interface Violation {
   violationType: violationTypes;
 }
 
+let dataBucket: string | undefined = process.env['DEVREL_SETTINGS_BUCKET'];
```
Comment (JustinBeckwith) [inline packages/snippet-bot/src/violations.ts:27]: This could be simplified to `const dataBucket = process.env.DEVREL_SETTINGS_BUCKET || 'devrel-prod-settings'`.

**Review by JustinBeckwith — APPROVED** [review]

File: packages/snippet-bot/src/violations.ts (hunk 1 above)
Comment (tmatsuo) [reply packages/snippet-bot/src/violations.ts]: Done

**Comment by tmatsuo** [comment]
Now the `products.json` file is in the prod bucket. Merging.
