### PR TITLE
fix(gcf-utils): skip suspended installations

### LINKED ISSUE #2157: bug(merge-on-green): SyncLabels cron scheduler dies with HttpError: This installation has been suspended
```
stack: "HttpError: This installation has been suspended
    at /workspace/node_modules/@octokit/request/dist-node/index.js:86:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getInstallationAuthentication (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:274:7)
    at async hook (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:433:7)
    at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:124:28)
    at async GCFBootstrapper.eachInstalledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:424:26)
    at async GCFBootstrapper.handleScheduledRepository (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:537:34)
    at async GCFBootstrapper.handleScheduled (/workspace/node_modules/gcf-utils/build/src/gcf-utils.js:377:13)
    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:289:21"
```

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #2157

### CODE REVIEW

File: packages/gcf-utils/src/gcf-utils.ts [hunk 1]
```diff
@@ -740,6 +740,11 @@ export class GCFBootstrapper {
       const promises: Array<Promise<void>> = new Array<Promise<void>>();
       const batchSize = 30;
       for await (const installation of installationGenerator) {
+        if (installation.suspended_at !== null) {
+          // Assume the installation is suspended.
+          logger.info(`skipping installations for ${installation.id} because it is suspended`);
```
Comment (chingor13) [inline packages/gcf-utils/src/gcf-utils.ts:745]: Probably need to do this for the `schedule.installation` fanout handler too

**Review by chingor13 — CHANGES_REQUESTED** [review]
Looks like we need to run the linter too

File: packages/gcf-utils/src/gcf-utils.ts (hunk 1 above)
Comment (tmatsuo) [reply packages/gcf-utils/src/gcf-utils.ts]: Sure, I moved it to eachInstallation

**Review by chingor13 — APPROVED** [review]
