### PR TITLE
fix(buildcop): sort dup closed issues by closed_at

### LINKED ISSUE #975: build-cop-bot: doesn't reopen most recently closed issue, so it always thinks the issue was closed > 10 days ago
If there are duplicate issues, we currently pick the one that was opened first. But, if there are duplicate _closed_ issues, that means we pick the one that was probably closed the longest time ago.

When deciding whether to reopen an issue as flaky or to create a new issue, the bot looks at how long ago the issue was closed. So, if the first issue was closed a really long time ago, the bot will _always_ think it should file a new issue.

We should take the close time into account when thinking about reopening an issue.

Example of where this came up: https://github.com/GoogleCloudPlatform/golang-samples/issues/1726

### PR DESCRIPTION
**Pull request by tbpg**
When deciding whether to reopen an old issue or to open a new one, we
want to find the old issue that was most recently closed. That way, if
the most recently closed issue was closed within 10 days, we know to
reopen it.

Fixes #975 🦕

### CODE REVIEW

File: packages/buildcop/src/buildcop.ts [hunk 1]
```diff
@@ -614,13 +611,25 @@ buildcop.issueComparator = (
...
   if (buildcop.isFlaky(a) && !buildcop.isFlaky(b)) {
     return -1;
   }
   if (!buildcop.isFlaky(a) && buildcop.isFlaky(b)) {
     return 1;
   }
-  return a.number - b.number;
+  const aClose = parseClosedAt(a.closed_at);
+  const bClose = parseClosedAt(b.closed_at);
+  if (aClose && bClose) {
```
Comment (JustinBeckwith) [inline packages/buildcop/src/buildcop.ts:629]: Just be careful about truthiness here.  This will evaluate false for undefined, null, and 0.  That may be fine since it's a date :)  I tend to prefer more strict checks.

**Review by JustinBeckwith — APPROVED** [review]

File: packages/buildcop/src/buildcop.ts (hunk 1 above)
Comment (tbpg) [reply packages/buildcop/src/buildcop.ts:629]: That seems OK for this particular case. This check would not be valid for any of those values. I suppose we know that the result is `number|undefined`, though.

I'm open here. Will defer to you for JS style.

Comment (JustinBeckwith) [reply packages/buildcop/src/buildcop.ts:629]: Nah this is fine, just shining light on it :)
