### PR TITLE
fix(snippet-bot): allow capital letters

### LINKED ISSUE #3599: [snippet-bot] Tag format checker doesn't allow capital letters used by snippet-gen
snippet-gen (automated snippet generation for gapic clients) specifies a region tag format that can include capital letters. (See internal document go/snippet-gen-design and search for the "Region tag format" section.) Currently snippet-bot is flagging these as a bad tag format because its regex disallows capital letters.

/cc @amanda-tarafa

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #3599

### CODE REVIEW

File: packages/snippet-bot/src/violations.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export interface Violation {
 
 const dataBucket = process.env.DEVREL_SETTINGS_BUCKET || 'devrel-prod-settings';
 
-const TAG_FORMAT_REGEX = /^([a-z0-9_])+$/;
+const TAG_FORMAT_REGEX = /^([a-zA-Z0-9_])+$/;
```
Comment (dazuma) [inline packages/snippet-bot/src/violations.ts:44]: I think this is now equivalent to `\w`.

Comment (tmatsuo) [reply packages/snippet-bot/src/violations.ts]: You're right!

**Review by bcoe — APPROVED** [review]
