### PR TITLE
fix(bot-config-utils): ignore 404 errors

### LINKED ISSUE #1911: bug(bot-config-utils): crashes with Not Found
I think the commit in the head branch is gone. I think we can wrap the whole method with try and ignore 404s.

Log
```
2021-05-28T23:49:50.994Zauto_label7w6eql4fnpkr HttpError: Not Found at /workspace/node_modules/@octokit/request/dist-node/index.js:68:23 at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:437:12) at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:62:26) at async ConfigChecker.validateConfigChanges (/workspace/node_modules/@google-automations/bot-config-utils/build/src/bot-config-utils.js:75:23) at async /workspace/build/src/auto-label.js:299:9 at async Promise.all (index 0) at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21
HttpError: Not Found at /workspace/node_modules/@octokit/request/dist-node/index.js:68:23 at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:437:12) at async Object.next (/workspace/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:62:26) at async ConfigChecker.validateConfigChanges (/workspace/node_modules/@google-automations/bot-config-utils/build/src/bot-config-utils.js:75:23) at async /workspace/build/src/auto-label.js:299:9 at async Promise.all (index 0) at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:228:21
```

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1911

### CODE REVIEW

File: packages/bot-config-utils/src/bot-config-utils.ts [hunk 1]
```diff
@@ -174,60 +175,70 @@ export class ConfigChecker<ConfigType> {
...
+        pull_number: prNumber,
+        per_page: 100,
+      };
+      let errorText = '';
+      const files = await octokit.paginate(
+        octokit.pulls.listFiles,
+        listFilesParams
+      );
+      for (const file of files) {
+        if (file.status === 'removed') {
```
Comment (sofisl) [inline packages/bot-config-utils/src/bot-config-utils.ts:194]: Should we log that we attempted to grab the file or somehow bubble up an alert? Won't it just fail silently down the line (since there's no config)? I might not be understanding the full context though.

Comment (tmatsuo) [reply packages/bot-config-utils/src/bot-config-utils.ts:194]: This code is iterating all the files in the PR:
- If it's removed, we just skip it
- If the filename is the bot's config file, we want to check the schema
- Also the filename looks to have a wrong file extension, we report that too

I don't think we need to do anything for 'removed' case.

**Review by sofisl — APPROVED** [review]
