### PR TITLE
fix: use graphql to promote PR from draft to ready for review

### LINKED ISSUE #5160: bug(owlbot): copy code PRs are not upgrade from draft to ready for review
PR https://github.com/googleapis/repo-automation-bots/issues/5034 added support for owlbot to create draft owlbot copy code PRs initially to avoid noisy notifications. Based on the text in the issue, I understand that draft PRs should be promoted once owlbot is finished with the post processing step, however after the post processing step, owl bot copy code PRs are remaining in draft status.

For example, see https://github.com/googleapis/repo-automation-bots/issues/5034

Also, see https://github.com/googleapis/repo-automation-bots/issues/5034#issuecomment-1645268061

### PR DESCRIPTION
**Pull request by SurferJeffAtGoogle**
Fixes #5160

### CODE REVIEW

File: packages/owl-bot/src/bin/commands/commit-post-processor-update.ts [hunk 1]
```diff
@@ -181,3 +195,38 @@ export function commitOwlbotUpdate(repoDir: string) {
...
+      }
+    }`,
+    {
+      owner: prLocator.owner,
+      repo: prLocator.repo,
+      pullNumber: prLocator.pull_number,
+    }
+  )) as any;  // eslint-disable-line
+
+  await octokit.graphql(
```
Comment (chingor13) [inline packages/owl-bot/src/bin/commands/commit-post-processor-update.ts:221]: Should we check the result of the first query in case we don't get the expected response?

File: packages/owl-bot/src/bin/commands/commit-post-processor-update.ts [hunk 2]
```diff
@@ -80,10 +80,28 @@ export const commitPostProcessorUpdateCommand: yargs.CommandModule<{}, Args> = {
...
-export async function commitPostProcessorUpdate(args: Args): Promise<void> {
+interface PRLocator {
+  owner: string;
+  repo: string;
+  pull_number: number;
+}
+
+interface AfterCommitPostProcessorUpdate {
+  /// When present, the pull request should be marked ready for review.
+  shouldPromoteFromDraft?: PRLocator;
```
Comment (chingor13) [inline packages/owl-bot/src/bin/commands/commit-post-processor-update.ts:99]: nit: this field name implies a boolean return type. Perhaps a name like `pullRequestToPromote` or something like that?

File: packages/owl-bot/test/commit-post-processor-update.ts [hunk 3]
```diff
@@ -142,17 +146,19 @@ describe('commitPostProcessorUpdate', () => {
...
-    await commitPostProcessorUpdate(prepareArgs(clone));
+    assert.deepStrictEqual(
+      (await commitPostProcessorUpdate(prepareArgs(clone)))
+        .shouldPromoteFromDraft,
+      {
+        owner: 'test-org',
+        pull_number: pr,
+        repo: 'test-repo',
+      }
+    );
```
Comment (chingor13) [inline packages/owl-bot/test/commit-post-processor-update.ts:157]: This test reads strangely to mean, hence my nit about the name of the `.shouldPromoteFromDraft` name.

**Review by chingor13 — CHANGES_REQUESTED** [review]

File: packages/owl-bot/test/commit-post-processor-update.ts (hunk 3 above)
Comment (SurferJeffAtGoogle) [reply packages/owl-bot/test/commit-post-processor-update.ts]: done

File: packages/owl-bot/src/bin/commands/commit-post-processor-update.ts (hunk 2 above)
Comment (SurferJeffAtGoogle) [reply packages/owl-bot/src/bin/commands/commit-post-processor-update.ts]: done

**Review by chingor13 — APPROVED** [review]
