### PR TITLE
fix: authenticate octokit instance properly when receiving payload from cloud scheduler

### LINKED ISSUE #1444: Sync repo settings failing to update settings?
https://github.com/googleapis/google-api-java-client/pull/1717#issuecomment-782274306

### PR DESCRIPTION
**Pull request by sofisl**
Fixes #1444, and hopefully a bunch of our other bots that use a cron job as well.

### CODE REVIEW

File: packages/gcf-utils/src/gcf-utils.ts [hunk 1]
```diff
@@ -381,11 +381,21 @@ export class GCFBootstrapper {
   }
 
   // TODO: How do we still get access to this installation token?
-  async getAuthenticatedOctokit(installationId: number): Promise<Octokit> {
+  async getAuthenticatedOctokit(
+    installationId: number,
+    wrapOptions?: WrapOptions
```
Comment (bcoe) [inline packages/gcf-utils/src/gcf-utils.ts:386]: do we have access to `wrapOptions` when we call `getAuthenticatedOctokit` wondering if we could pass it in?

File: packages/gcf-utils/src/gcf-utils.ts [hunk 2]
```diff
@@ -381,11 +381,21 @@ export class GCFBootstrapper {
...
+  ): Promise<Octokit> {
     // See: https://github.com/probot/probot/issues/1003
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
-    const app = (this.probot as any).apps[0] as Probot;
-    return ((await app.auth(installationId)) as unknown) as Octokit;
+    const cfg = await this.getProbotConfig(wrapOptions?.logging);
+    return new Octokit({
```
Comment (bcoe) [inline packages/gcf-utils/src/gcf-utils.ts:391]: I think rather than `new cfg. Octokit` because we add a couple plugins to Octokit when loading the config.

**Review by bcoe — CHANGES_REQUESTED** [review]

**Review by bcoe — APPROVED** [review]
