### PR TITLE
fix: restrict snippet bot to only be allowed to run for google org for all actions

### LINKED ISSUE #5615: Snippet bot queue has a backup
currently there are 262 jobs in the snippet bot queue

### PR DESCRIPTION
**Pull request by ldetmer**
We weren't restricting all snippetbot actions to google org, fixed so now all are blocked

As part of this fix had to migrate all test data to use an allowlisted repo

Fixes #5615  🦕

### CODE REVIEW

File: packages/snippet-bot/src/snippet-bot.ts [hunk 1]
```diff
@@ -85,7 +85,8 @@ const REFRESH_STRING = '- [x] Refresh this comment';
 // Github issue comment API has a limit of 65536 characters.
 const MAX_CHARS_IN_COMMENT = 64000;
 
-const ALLOWED_ORGANIZATIONS = ['googleapis', 'GoogleCloudPlatform'];
+//tmatsuo is present for testing
```
Comment (meltsufin) [inline packages/snippet-bot/src/snippet-bot.ts:88]: tmatsuo no longer works on the project. Please remove them from the allow-list.

Comment (ldetmer) [reply packages/snippet-bot/src/snippet-bot.ts]: done, I had to update all the test data to use an allowlisted repo (before it was tmatsuo)
