### PR TITLE
Fix: issue 1021 where auto-label bot needs to catch "config not found" on installation

### LINKED ISSUE #1021: Bug: auto-label on installation has HttpError: Not Found
I caused this. Will fix asap

```json
{
  "insertId": "000000-22e3f7c3-ae81-4760-862d-ac1d5cafce89",
  "jsonPayload": {
    "trigger": {
      "github_delivery_guid": "4ae0a200-0919-11eb-8e17-6c1f72bdb25a",
      "trigger_type": "Cloud Task"
    },
    "name": "AggregateError",
    "message": "\n    HttpError: Not Found\n        at /workspace/node_modules/@octokit/request/dist-node/index.js:66:23\n        at runMicrotasks (<anonymous>)\n        at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:392:12)\n        at async /workspace/build/src/auto-label.js:303:30\n        at async Promise.all (index 0)\n        at async Promise.all (index 0)\n        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:172:21",
    "event": {
      "payload": {
        "requester": null,
        "action": "created",
        "installation": {
          "suspended_at": null,
          "repository_selection": "all",
          "suspended_by": null,
          "events": [
            "issues",
            "pull_request"
          ],
          "target_type": "User",
          "permissions": {
            "pull_requests": "write",
            "metadata": "read",
            "single_file": "read",
            "issues": "write"
          },
          "access_tokens_url": "https://api.github.com/app/installations/12271281/access_tokens",
          "app_id": 52415,
          "html_url": "https://github.com/settings/installations/12271281",
          "created_at": "2020-10-07T20:49:40.000-07:00",
          "account": {
            REDACTED
          },
          "updated_at": "2020-10-07T20:49:40.000-07:00",
          "repositories_url": "https://api.github.com/installation/repositories",
          "app_slug": "product-auto-label",
          "single_file_name": ".github/auto-label.yaml",
          "id": 12271281,
          "target_id": 22240100
        },
        "repositories": [
                      REDACTED
      },
      "id": "4ae0a200-0919-11eb-8e17-6c1f72bdb25a",
      "name": "installation"
    },
    "type": "Error",
    "level": 50,
    "errors": [
      {
     
            },
            "installation": {
              "permissions": {
                "issues": "write",
                "single_file": "read",
                "pull_requests": "write",
                "metadata": "read"
              },
              "repository_selection": "all",
              "suspended_at": null,
              "access_tokens_url": "https://api.github.com/app/installations/12271281/access_tokens",
              "events": [
                "issues",
                "pull_request"
              ],
              "updated_at": "2020-10-07T20:49:40.000-07:00",
              "id": 12271281,
              "repositories_url": "https://api.github.com/installation/repositories",
              "account": {
                         REDACTED
              },
              "single_file_name": ".github/auto-label.yaml",
              "suspended_by": null,
              "html_url": "https://github.com/settings/installations/12271281",
              "app_slug": "product-auto-label",
              "target_type": "User",
              "app_id": 52415,
              "target_id": 22240100,
              "created_at": "2020-10-07T20:49:40.000-07:00"
            }
          },
          "id": "4ae0a200-0919-11eb-8e17-6c1f72bdb25a"
        },
        "request": {
          "headers": {
            "accept": "application/vnd.github.v3+json",
            "authorization": "token [REDACTED]",
            "user-agent": "octokit-rest.js/18.0.6 octokit-core.js/3.1.2 Node.js/12.18.3 (linux; x64)"
          },
                 REDACTED
          "method": "GET",
          "request": {}
        },
        "name": "HttpError",
        "status": 404,
        "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"
      }
    ],
    "stack": "AggregateError: \n    HttpError: Not Found\n        at /workspace/node_modules/@octokit/request/dist-node/index.js:66:23\n        at runMicrotasks (<anonymous>)\n        at async sendRequestWithRetries (/workspace/node_modules/@octokit/auth-app/dist-node/index.js:392:12)\n        at async /workspace/build/src/auto-label.js:303:30\n        at async Promise.all (index 0)\n        at async Promise.all (index 0)\n        at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:172:21\n    at /workspace/node_modules/@octokit/webhooks/dist-node/index.js:111:19\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Promise.all (index 0)\n    at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:172:21"
  },
  "resource": {
    "type": "cloud_function",
    "labels": {
      "region": "us-central1",
      "project_id": "repo-automation-bots",
      "function_name": "auto_label"
    }
  },
  "timestamp": "2020-10-08T12:39:46.919Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "htv5plwpamal"
  },
  "logName": "projects/repo-automation-bots/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/repo-automation-bots/traces/de94351bb0c942d5865720f43436173f",
  "receiveTimestamp": "2020-10-08T12:39:54.781482195Z"
}
```

### PR DESCRIPTION
**Pull request by nicoleczhu**
Fixes #1021 

Added test to make sure default configs are used when there's no custom user config

### CODE REVIEW

**Review by bcoe — APPROVED** [review]

File: packages/auto-label/src/auto-label.ts [hunk 1]
```diff
@@ -388,11 +388,17 @@ export function handler(app: Application) {
...
 
       // Looks for a config file, breaks if user disabled product labels
-      const response = await context.github.repos.getContent({
-        owner,
-        repo,
-        path: '.github/auto-label.yaml',
-      });
+      let response;
+      try {
+        response = await context.github.repos.getContent({
```
Comment (bcoe) [inline packages/auto-label/src/auto-label.ts:393]: nit: there's a helper for this `context.github.config`, which we use in some of the libraries like `release-please`; I believe this suppresses the error, such that we wouldn't have bumped into this.

Doesn't need to be a blocker for this hot fix.
