### PR TITLE
fix: handle PR with greater than 100 commits

### LINKED ISSUE #5188: conventionalcommit: hangs on large pull requests
I have a [PR](https://github.com/googleapis/google-cloud-go/pull/8397) with 100+ commits changing 2k+ files. The `conventionalcommit` check is hanging and blocking the pull request (as it is required). 

I was told that logs indicate every single file touched is being logged which could mean some expensive operation is freezing up the check.

cc: @bcoe

### PR DESCRIPTION
**Pull request by bcoe**
Fixes #5188

### CODE REVIEW

File: packages/conventional-commit-lint/src/utils.ts [hunk 1]
```diff
@@ -69,9 +69,16 @@ export async function scanPullRequest(
...
 
-  let commits: PullsListCommitsResponseData;
+  const commits: PullsListCommitsResponseData = [];
   try {
-    commits = (await octokit.pulls.listCommits(commitParams)).data;
+    for await (const response of octokit.paginate.iterator(
+      octokit.rest.pulls.listCommits,
+      commitParams
+    )) {
+      for (const commit of response.data) {
```
Comment (SurferJeffAtGoogle) [inline packages/conventional-commit-lint/src/utils.ts:78]: Code Golf:
```
commits.push(...response.data);
```

**Review by SurferJeffAtGoogle — APPROVED** [review]

File: packages/conventional-commit-lint/src/utils.ts [hunk 2]
```diff
@@ -69,9 +69,16 @@ export async function scanPullRequest(
...
+        commits.push(commit);
+      }
```
Comment (chingor13) [inline packages/conventional-commit-lint/src/utils.ts:80]:
```suggestion
      commits.push(...response.data);
```
