### PR TITLE
fix(snippet-bot): apply ignoreFiles to violation checks

### LINKED ISSUE #1106: bug(snippet-bot): ignoreFiles configuration is not applied to violation warnings
Currently `ignoreFiles` configuration is only applied to the checks for mismatched region tags. We should apply this configuration for checks for other violations.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1106

I also needed to factor out some config related stuff for exporting.

### CODE REVIEW

**Comment by tmatsuo** [comment]
Just rebased

File: packages/snippet-bot/src/snippet-bot.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@
 /* eslint-disable node/no-extraneous-import */
 
 import {Application} from 'probot';
+import {Configuration, ConfigurationOptions} from './configuration';
```
Comment (JustinBeckwith) [inline packages/snippet-bot/src/snippet-bot.ts:19]: Typically you group these imports together

**Review by JustinBeckwith — APPROVED** [review]
