### PR TITLE
fix: add error logging when user is not authorized to push to a branch

### LINKED ISSUE #558: Merge-on-green: let people know if MOG doesn't have access to push to a branch.
This has happened before when merging: 
https://screenshot.googleplex.com/uPCiQ49QgdN.png

We need to tell the user this is happening. They need to resolve by doing the following:
https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions
https://screenshot.googleplex.com/ZQwEM7zidft.png

### PR DESCRIPTION
**Pull request by sofisl**
Fixes #558: adds error logging when user is not authorized to push to a branch, and ensures that comments are only submitted once

### CODE REVIEW

File: packages/merge-on-green/src/merge-logic.ts [hunk 1]
```diff
@@ -31,6 +31,10 @@ interface Reviews {
   state: string;
 }
 
+interface Comments {
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:34]: Single comment rather than plural?

```suggestion
interface Comment {
```

File: packages/merge-on-green/src/merge-logic.ts [hunk 2]
```diff
@@ -669,6 +692,17 @@ export async function mergeOnGreen(
       await mergeOnGreen.merge(owner, repo, pr, prInfo, github);
       merged = true;
     } catch (err) {
+      if (err.message.includes('not authorized to push to this branch')) {
+        let isCommented;
+        if (commentsOnPR.length !== 0) {
+          isCommented = commentsOnPR.find(element =>
+            element.body.includes('not authorized to push to this branch')
+          );
+        }
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:701]:
```suggestion
        const isCommented = commentsOnPR?.find(element =>
          element.body.includes('not authorized to push to this branch')
        );
```

File: packages/merge-on-green/src/merge-logic.ts [hunk 3]
```diff
@@ -669,6 +692,17 @@ export async function mergeOnGreen(
       await mergeOnGreen.merge(owner, repo, pr, prInfo, github);
       merged = true;
     } catch (err) {
+      if (err.message.includes('not authorized to push to this branch')) {
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:695]: Is this error message from the API? Is there a 403 response code or something we can use? I'm concerned this string might change.

File: packages/merge-on-green/src/merge-logic.ts [hunk 4]
```diff
@@ -688,13 +722,21 @@ export async function mergeOnGreen(
...
-          pr,
-          conflictMessage,
-          github
-        );
+        let isCommented;
+        if (commentsOnPR.length !== 0) {
+          isCommented = commentsOnPR.find(element =>
+            element.body.includes('PR has conflicts that you need to resolve')
+          );
+        }
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:730]:
```suggestion
        const isCommented = commentsOnPR.find(element =>
          element.body.includes('PR has conflicts that you need to resolve')
        );
```

File: packages/merge-on-green/src/merge-logic.ts [hunk 5]
```diff
@@ -705,8 +747,16 @@ export async function mergeOnGreen(
     await mergeOnGreen.commentOnPR(owner, repo, pr, failedMesssage, github);
     return true;
   } else if (state === 'comment') {
+    let isCommented;
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:750]: Same suggestion.

File: packages/merge-on-green/src/merge-logic.ts [hunk 6]
```diff
@@ -669,6 +692,14 @@ export async function mergeOnGreen(
       await mergeOnGreen.merge(owner, repo, pr, prInfo, github);
       merged = true;
     } catch (err) {
+      if (err.status === 405) {
+        const isCommented = commentsOnPR?.find(element =>
+          element.body.includes('not authorized to push to this branch')
+        );
+        if (!isCommented) {
+          await mergeOnGreen.commentOnPR(owner, repo, pr, err.message, github);
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:700]: Looks like this still depends on the content of the API error message. Perhaps make this a `const` and use it on both lines?

File: packages/merge-on-green/src/merge-logic.ts [hunk 7]
```diff
@@ -705,8 +741,13 @@ export async function mergeOnGreen(
     await mergeOnGreen.commentOnPR(owner, repo, pr, failedMesssage, github);
     return true;
   } else if (state === 'comment') {
+    const isCommented = commentsOnPR?.find(element =>
+      element.body.includes('PR has attempted to merge for 3 hours')
```
Comment (tbpg) [inline packages/merge-on-green/src/merge-logic.ts:745]: Make a `const`?

File: packages/merge-on-green/src/merge-logic.ts (hunk 6 above)
Comment (sofisl) [reply packages/merge-on-green/src/merge-logic.ts:700]: Ah! This actually depends on the content of the comments in the PR. So, really it's just checking to make sure I didn't  already put the message there before. But, you're right that that message could change, so I can make a wrapper for that message and check the wrapper so I can ensure consistency!

File: packages/merge-on-green/test/merge-on-green.ts [hunk 8]
```diff
@@ -45,6 +45,10 @@ interface CheckRuns {
   check_runs: [{name: string; conclusion: string}];
 }
 
+interface Comments {
```
Comment (tbpg) [inline packages/merge-on-green/test/merge-on-green.ts:48]:
```suggestion
interface Comment {
```
