### PR TITLE
fix(snippet-bot): disable warning for removal of region tags in use

### LINKED ISSUE #1145: bug(snippet-bot): disable warnings for removal of region tags in use
It turned out that the data we have now is not the right one. We should disable this feature for now.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #1145

### CODE REVIEW

File: packages/snippet-bot/src/snippet-bot.ts [hunk 1]
```diff
@@ -425,20 +421,9 @@ ${bodyDetail}`
         result,
         configuration
       );
-      // Check for removing region tags in use.
-      const removeViolations = await checkRemovingUsedTagViolations(
```
Comment (JustinBeckwith) [inline packages/snippet-bot/src/snippet-bot.ts:429]: It makes me slightly nervous that we're able to delete this code with no test changes :)  LGTM assuming CI is passing.  Can we get an issue in the tracker that outlines what's broken, and reminds us to add this back though?

**Review by JustinBeckwith — APPROVED** [review]

File: packages/snippet-bot/src/snippet-bot.ts (hunk 1 above)
Comment (tmatsuo) [reply packages/snippet-bot/src/snippet-bot.ts:429]: Ya, there was no `calledOnce` type assert ;)

Will open a new issue about enabling this.

Comment (tmatsuo) [reply packages/snippet-bot/src/snippet-bot.ts:429]: https://github.com/googleapis/repo-automation-bots/issues/1147
