### PR TITLE
fix(release-brancher): use "ci:" (non-releasable) in init

### LINKED ISSUE #2568: release-brancher: allow customization of pull request to default branch
Allow the developer running the script to either customize the PR title and body and commit message.

### PR DESCRIPTION
**Pull request by suztomo**
Use "ci: " suffix in the commit message when it creates a workflow pull request for initializing the protected branch. This addresses @chingor13 's comment in https://github.com/googleapis/repo-automation-bots/pull/2615#discussion_r717957080

Fixes #2568 🦕

### CODE REVIEW

File: packages/release-brancher/__snapshots__/release-brancher.js [hunk 1]
```diff
@@ -272,3 +282,15 @@ exports['workflows-pr-options'] = {
   "force": true,
   "fork": false
 }
+
+exports['workflows-pr-options-java-backport'] = {
+  "upstreamRepo": "testRepo",
+  "upstreamOwner": "testOwner",
+  "message": "ci: configure the protected branch",
+  "title": "ci: configure the protected branch",
```
Comment (suztomo) [inline packages/release-brancher/__snapshots__/release-brancher.js:290]: This is the effect of this PR.

File: packages/release-brancher/src/release-brancher.ts [hunk 2]
```diff
@@ -336,7 +336,12 @@ export class Runner {
         }
       }
     }
-    const message = 'feat: configure the protected branch';
+
+    // For java-lts type, we want a release through a releasable commit ('feat: ') immediately
+    // after creating the protected branch.
+    const message =
+      (this.releaseType === 'java-lts' ? 'feat' : 'ci') +
```
Comment (suztomo) [inline packages/release-brancher/src/release-brancher.ts:343]: I think we need to have condition based on the releaseType.

**Review by chingor13 — APPROVED** [review]
